# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 05:50
from __future__ import unicode_literals

import acrawriter.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=acrawriter.django.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=acrawriter.django.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body_html',
            field=acrawriter.django.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=acrawriter.django.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=acrawriter.django.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary_html',
            field=acrawriter.django.TextField(),
        ),
    ]
