# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 09:33
from __future__ import unicode_literals

from django.db import migrations


def forwards(app, schema_editor):
    # need to drop indexes for correct alter table from varchar to bytea
    try:
        schema_editor.execute('alter table members_individualmember drop CONSTRAINT if exists members_developermember_email_key;')
        schema_editor.execute('drop index members_developermember_email_41cc5976_like;')
    except Exception as exc:
        print(exc)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_individual_members'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
