# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 09:35
from __future__ import unicode_literals

import acrawriter.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170306_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatemember',
            name='billing_email',
            field=acrawriter.django.EmailField(blank=True, help_text='If different from contact email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='corporatemember',
            name='contact_email',
            field=acrawriter.django.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='email',
            field=acrawriter.django.EmailField(max_length=254, unique=True),
        ),
    ]
