# Generated by Django 2.2.24 on 2021-12-01 10:34

import acrawriter.django
from django.db import migrations


def forwards(app, schema_editor):
    # need to drop indexes for correct alter table from varchar to bytea
    try:
        schema_editor.execute('alter table members_individualmember drop CONSTRAINT if exists members_developermember_email_key;')
        schema_editor.execute('drop index members_developermember_email_41cc5976_like;')
    except Exception as exc:
        print(exc)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20181001_1031'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='corporatemember',
            name='billing_email',
            field=acrawriter.django.EmailField(blank=True, help_text='If different from contact email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='corporatemember',
            name='contact_email',
            field=acrawriter.django.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='email',
            field=acrawriter.django.EmailField(max_length=254, unique=True),
        ),
    ]
